### ISSUE TITLE
open_channel fields not byte aligned

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lightning-rfc#407]
```
open_channel,32
open_channel,0,chain_hash,32
open_channel,32,temporary_channel_id,32
open_channel,64,funding_satoshis,8
open_channel,72,push_msat,8
open_channel,80,dust_limit_satoshis,8
open_channel,88,max_htlc_value_in_flight_msat,8
open_channel,96,channel_reserve_satoshis,8
open_channel,104,htlc_minimum_msat,8
open_channel,112,feerate_per_kw,4
open_channel,116,to_self_delay,2
open_channel,118,max_accepted_htlcs,2
open_channel,120,funding_pubkey,33
open_channel,153,revocation_basepoint,33
open_channel,186,payment_basepoint,33
open_channel,219,delayed_payment_basepoint,33
open_channel,252,htlc_basepoint,33
open_channel,285,first_per_commitment_point,33
open_channel,318,channel_flags,1
Traceback (most recent call last):
  File "extract-formats.py", line 165, in <module>
    main(options, args)
  File "extract-formats.py", line 115, in main
    align))
ValueError: 570:message open_channel field shutdown_len Offset 319 not aligned on 2 boundary:
```

Is this intentional?

**Comment by rustyrussell** [comment]
The original design goal for the protocol (at request of @adiabat ) was that fields be naturally alligned.  That proved harder and harder to maintain as the protocol evolved, particularly with features adding fields.
